### ISSUE TITLE
how to convert alos2 ceos to geotiff

### ISSUE THREAD

**Issue by zyxgis** [isce-framework/isce3#13]
how to use isce3 to directly convert alos2 ceos  to geotiff

**Comment by ghost** [comment]
﻿﻿I don't think isce3 has a command-line tool for this.

In Python you could read the file using the CEOS parser and then write it to GeoTIFF using the GDAL API. The `alos2_to_nisar_l1.py` script shows how to use the CEOS parser. But that's not what I'd call "direct".
