### ISSUE TITLE
When will you plan to release the first stable edition?

### ISSUE THREAD

**Issue by kanglcn** [isce-framework/isce3#3]
Hi! Just as the title.

**Comment by rtburns-jpl** [comment]
We're currently beholden to [NISAR](https://en.wikipedia.org/wiki/NISAR_(satellite))'s needs, so I wouldn't expect much stability until after launch. Until we focus on general-purpose SAR capabilities in isce3, your needs will probably be better-suited by [isce2](https://github.com/isce-framework/isce2).
