### ISSUE TITLE
whether  It can process data of GF-3

### ISSUE THREAD

**Issue by boost66** [isce-framework/isce3#4]
whether  It can process data of GF-3

**Comment by gmgunter** [comment]
Hi @boost66. Unfortunately, isce3 doesn't currently have support for GF-3 data. Most of the development right now is focused on supporting the upcoming NISAR mission. [isce2](https://github.com/isce-framework/isce2) has much more robust sensor support at the moment, though I'm not sure whether or not it supports GF-3 products specifically. You may want to consider opening an issue on that repository for more info.
